spring:
  datasource:
    url: jdbc:mysql://localhost:3306/handsome_man?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin123
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    timeout: PT30M
server:
  port: 80