spring:
  datasource:
    url: jdbc:mysql://cdb-7avjsz3g.bj.tencentcdb.com:10219/sever_index?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin827189
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    timeout: PT30M
server:
  port: 80