spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
  mail:
    host: smtp.qq.com
    password: jcrwjaievqypcbcj
    username: 479634319@qq.com
    port: 465
    protocol: smtp
    from: 479634319@qq.com
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
rsa:
  encrypt:
    open: true
    showLog: true
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmTjqU3LAgHnHkXMwwnbcM7xBnPvJToeEi9ubESCHVzBbxeXES2uLkWJ1FNyv8dmAmLjrB/1RifzT0zCgeMG/i3lyLcZHmMIbP37V3mSsV9A3nXwcLQtsghdP1Orn8nat6++py9HkrXm+UyHmF8XcLiTIYv2l0oPuxl5a0IXQ67pfMyCEVwJGtx9RVZIvOiZRI4QKv2CPZQp0D1N5U3lurATKLGr0d38jmXRG3eyjIig3BT/+1nspj/jVuBqNJdgmi+uBjesW8QUB4+afddqzw7Ro7rBeU/WKIeXDOrSBHl7jFzeZ6CC+rso+lYm+TxmqZwkAlTuTR6co6Tcn2xKE2QIDAQAB
    privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCZOOpTcsCAeceRczDCdtwzvEGc+8lOh4SL25sRIIdXMFvF5cRLa4uRYnUU3K/x2YCYuOsH/VGJ/NPTMKB4wb+LeXItxkeYwhs/ftXeZKxX0DedfBwtC2yCF0/U6ufydq3r76nL0eSteb5TIeYXxdwuJMhi/aXSg+7GXlrQhdDrul8zIIRXAka3H1FVki86JlEjhAq/YI9lCnQPU3lTeW6sBMosavR3fyOZdEbd7KMiKDcFP/7WeymP+NW4Go0l2CaL64GN6xbxBQHj5p912rPDtGjusF5T9Yoh5cM6tIEeXuMXN5noIL6uyj6Vib5PGapnCQCVO5NHpyjpNyfbEoTZAgMBAAECggEAXDamwAYl2Kxx8RWUWNTT/cbk7ieSpdJlcQ5/qrUa/tw5v0Zi9skIvDy3HhEbSsCN5lwUB0Drm9IvYcC4MzTXpIc4slfMqyDW6UXaTPflyQulDQCurGVdroV9JDUj1waZ8Y7Rb7sol0bXxox2QARyWMsGVp00+Rcx0uziVvDSJaubtWpkfaP6v7BfYcPn7i56AoyUrb7dkkQgMuousMxN6uxsRu+nfxTDXX8rGjXd+1TlursbE+1AqnZMGW4u4ShxPJwpWAdDUWye74OajipK1UFne7Y1gyr+55tEt/kGxlCbzpKYWEy9HNQBdVQ3VOiEfnwKU68PtboN+3AAYskNIQKBgQDUpYLyLOUNTtlVSTiwfFUAAqPudsxYH2Jz/p6ImWAGM3DMJedjs265qBHQQvsyZwXV6PdweQjfkiJbfs5qPUyhqKjXkmdBGnTOHpKWM8SR8BR0qnK2BVP92a6/fgWq5WRmybS5CUuMapGsEox1j7t0kQwXXgN2Nhb+q+5iopBFFQKBgQC4deyjrP/YdCgiVB0Yl73RbUPqAXIRLaFWgzXiT8PEaHdjHQK2YVqwT8rnvUw6lEAPaPG9ZtsHkbZLLqAH9sOBAzX0r/lezA/ebqm8od5OlqAKTRvivTNdMh62PrCwMThDAnO15bFYripUiAPjIyRA7Z9+bA5iH3RV30Mp6PA5tQKBgQCVDqvafFPW30WC/f+J3q1qg29L8eRNhTprGrkgAXsI/bf8sjkfbyCXbVOHS9xvOT4i8tm38m+g3/vLbPjeCbgUvXgVHB/ax+PGtDGGriUFM2fzW6NrKhL1J0jSHFF2uLOHRa6z4eseM3mHR71DjwwUqrPyEUmV7FZ0ECra4x8D/QKBgArPloPtQr1r6WJBrcbgNdbNYZqYZRgOpZMNc54E8MNVIBImBB+uSwNkWc8FMC+KuspsayafnZyu9JEpdWWiF8k65/GkUqg0q4Vs1PPiRMY0W8LezBCY6CbBJj2mJPLen56FyURS5vb8liyIIDoyuBA6HQvqx1kG4OmbgTM2nMW1AoGAe2dDmCvaH2ysMcQnHmTMtGsscKGtgkrPYpZ9jZHqkmvBLCwHs2twaXYaRLieE+oIWse8IbjBjVSiljlCECVPcid10pOnIbwA1RvVhnaDg7zbgHNhvST1u08bOQ4JDWIGjNKbn9kUaGkheNGSFaXb9yayn1qF6Rq+BR0h1+x1cok=

mybatis:
  configuration:
    map-underscore-to-camel-case: true